-- ===================
-- FARM MANAGEMENT
-- ===================

-- -------------------------
-- ENUM TYPES
-- -------------------------

CREATE TYPE financial_record AS ENUM (
    'przychod',
    'koszt'
);

CREATE TYPE kind_of_animal AS ENUM (
    'bydlo',
    'swinie',
    'konie',
    'owce',
    'kozy'
);

CREATE TYPE animal_sex AS ENUM (
    'samiec',
    'samica'
);

CREATE TYPE fields_type AS ENUM (
    'grunty_orne',
    'laka',
    'sad'
);

CREATE TYPE fieldwork_method AS ENUM (
    'wlasna',
    'usluga_zewnetrzna'
);

CREATE TYPE type_of_fieldwork AS ENUM (
    'orka',
    'talerzowanie',
    'agregatowanie',
    'siew',
    'koszenie',
    'zgrabianie',
    'przewracanie',
    'oprysk',
    'nawozenie',
    'zbior',
    'prasowanie',
    'inne'
);

CREATE TYPE financial_record_type AS ENUM (
    'sprzedaz',
    'zakup',
    'paliwo',
    'nawozy',
    'sor',
    'uslugi',
    'inne'
);

CREATE TYPE animals_utility AS ENUM (
    'miesny',
    'mleczny',
    'ogolnouzytkowy'
);

-- -------------------------
-- TABLES
-- -------------------------

CREATE TABLE farm (
    farm_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    fid_numer INTEGER NOT NULL UNIQUE,
    position VARCHAR(100),
    info TEXT
);

CREATE TABLE fields (
    field_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id INTEGER NOT NULL,
    type fields_type NOT NULL,
    position VARCHAR(100),
    area DOUBLE PRECISION NOT NULL CHECK (area > 0),
    CONSTRAINT fk_fields_farm
        FOREIGN KEY (farm_id) REFERENCES farm(farm_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE crops (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(64) NOT NULL,
    area DOUBLE PRECISION NOT NULL CHECK (area > 0),
    year INTEGER NOT NULL,
    CONSTRAINT fk_crops_field
        FOREIGN KEY (field_id) REFERENCES fields(field_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE animals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id INTEGER NOT NULL,
    aid_numer VARCHAR(255) NOT NULL UNIQUE,
    kind kind_of_animal NOT NULL,
    race VARCHAR(64) NOT NULL,
    utility animals_utility NOT NULL,
    sex animal_sex NOT NULL,
    date_of_birth DATE NOT NULL,
    CONSTRAINT fk_animals_farm
        FOREIGN KEY (farm_id) REFERENCES farm(farm_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE machines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id INTEGER NOT NULL,
    type VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    model VARCHAR(64) NOT NULL,
    manufacture INTEGER,
    CONSTRAINT fk_machines_farm
        FOREIGN KEY (farm_id) REFERENCES farm(farm_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_machine_year
        CHECK (manufacture IS NULL OR manufacture BETWEEN 1900 AND 2100)
);

CREATE TABLE fieldwork (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id INTEGER NOT NULL,
    type_of_work type_of_fieldwork NOT NULL,
    method fieldwork_method NOT NULL,
    date DATE NOT NULL,
    cost DOUBLE PRECISION CHECK (cost IS NULL OR cost >= 0),
    CONSTRAINT fk_fieldwork_field
        FOREIGN KEY (field_id) REFERENCES fields(field_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE financial_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id INTEGER NOT NULL,
    type financial_record NOT NULL,
    category financial_record_type NOT NULL,
    amount DOUBLE PRECISION NOT NULL CHECK (amount >= 0),
    performer VARCHAR(64) NOT NULL,
    date DATE NOT NULL,
    info TEXT,
    CONSTRAINT fk_financial_records_farm
        FOREIGN KEY (farm_id) REFERENCES farm(farm_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- ==================
-- SAMPLE DATA
-- =================


INSERT INTO farm (name, fid_numer, position, info)
VALUES (
    'Gospodarstwo Rolne Nowak',
    100001,
    'okolice Piły',
    'Gospodarstwo mieszane, produkcja roślinna i hodowla bydła.'
);


INSERT INTO fields (farm_id, type, position, area) VALUES
(1, 'grunty_orne', 'Pole 1 - przy gospodarstwie', 5.00),
(1, 'grunty_orne', 'Pole 2 - zachód', 8.50),
(1, 'laka', 'Łąka 1 - południe', 4.00);


INSERT INTO crops (field_id, name, type, area, year) VALUES
(1, 'pszenica ozima', 'zboze', 5.00, 2023),
(1, 'kukurydza', 'zboze', 5.00, 2024),
(1, 'ziemniaki', 'okopowe', 0.50, 2025),
(1, 'kukurydza', 'zboze', 4.50, 2025),
(2, 'rzepak ozimy', 'oleiste', 8.50, 2023),
(2, 'pszenica ozima', 'zboze', 8.50, 2024),
(2, 'kukurydza', 'zboze', 8.50, 2025),
(3, 'trawa', 'trawy', 4.00, 2023),
(3, 'trawa', 'trawy', 4.00, 2024),
(3, 'trawa', 'trawy', 4.00, 2025);


INSERT INTO animals (farm_id, aid_numer, kind, race, utility, sex, date_of_birth) VALUES
    (1, 'PL142001001', 'bydlo', 'HF', 'mleczny', 'samica', '2021-02-14'),
    (1, 'PL142001002', 'bydlo', 'HF', 'mleczny', 'samica', '2021-05-09'),
    (1, 'PL142001003', 'bydlo', 'HF', 'mleczny', 'samiec', '2021-07-21'),
    (1, 'PL142001004', 'bydlo', 'Jersey', 'mleczny', 'samica', '2022-01-03'),
    (1, 'PL142001005', 'bydlo', 'Jersey', 'mleczny', 'samica', '2022-03-17'),
    (1, 'PL142001006', 'bydlo', 'Jersey', 'mleczny', 'samiec', '2022-06-28'),
    (1, 'PL142001007', 'bydlo', 'Montbeliarde', 'mleczny', 'samica', '2022-09-11'),
    (1, 'PL142001008', 'bydlo', 'Montbeliarde', 'mleczny', 'samica', '2022-11-22'),
    (1, 'PL142001009', 'bydlo', 'Simmental', 'miesny', 'samiec', '2023-01-15'),
    (1, 'PL142001010', 'bydlo', 'Simmental', 'miesny', 'samica', '2023-03-29'),
    (1, 'PL142001011', 'bydlo', 'Simmental', 'miesny', 'samica', '2023-05-12'),
    (1, 'PL142001012', 'bydlo', 'HF', 'mleczny', 'samica', '2023-06-24'),
    (1, 'PL142001013', 'bydlo', 'HF', 'mleczny', 'samica', '2023-08-07'),
    (1, 'PL142001014', 'bydlo', 'HF', 'mleczny', 'samiec', '2023-10-19'),
    (1, 'PL142001015', 'bydlo', 'Limousin', 'miesny', 'samiec', '2023-12-02'),
    (1, 'PL142001016', 'bydlo', 'Limousin', 'miesny', 'samica', '2024-01-26'),
    (1, 'PL142001017', 'bydlo', 'Limousin', 'miesny', 'samica', '2024-03-08'),
    (1, 'PL142001018', 'bydlo', 'HF', 'mleczny', 'samica', '2024-04-21'),
    (1, 'PL142001019', 'bydlo', 'HF', 'mleczny', 'samica', '2024-06-03'),
    (1, 'PL142001020', 'bydlo', 'HF', 'mleczny', 'samica', '2024-07-16'),
    (1, 'PL142001021', 'bydlo', 'Jersey', 'mleczny', 'samica', '2024-08-28'),
    (1, 'PL142001022', 'bydlo', 'Jersey', 'mleczny', 'samiec', '2024-10-10'),
    (1, 'PL142001023', 'bydlo', 'Simmental', 'miesny', 'samica', '2024-11-23'),
    (1, 'PL142001024', 'bydlo', 'Simmental', 'miesny', 'samiec', '2025-01-05'),
    (1, 'PL142001025', 'bydlo', 'HF', 'mleczny', 'samica', '2025-02-18'),
    (1, 'PL142001026', 'bydlo', 'HF', 'mleczny', 'samica', '2025-04-01'),
    (1, 'PL142001027', 'bydlo', 'HF', 'mleczny', 'samiec', '2025-05-14'),
    (1, 'PL142001028', 'bydlo', 'Montbeliarde', 'mleczny', 'samica', '2025-06-26'),
    (1, 'PL142001029', 'bydlo', 'Montbeliarde', 'mleczny', 'samica', '2025-08-09'),
    (1, 'PL142001030', 'bydlo', 'Limousin', 'miesny', 'samiec', '2025-09-22'),
    (1, 'PL142001031', 'bydlo', 'Limousin', 'miesny', 'samica', '2025-10-17'),
    (1, 'PL142001032', 'bydlo', 'HF', 'mleczny', 'samica', '2025-11-29'),
    (1, 'PL142001033', 'bydlo', 'HF', 'mleczny', 'samica', '2026-01-11'),
    (1, 'PL142001034', 'bydlo', 'HF', 'mleczny', 'samiec', '2026-02-23'),
    (1, 'PL142001035', 'bydlo', 'Jersey', 'mleczny', 'samica', '2026-03-18'),
    (1, 'PL142001036', 'bydlo', 'Jersey', 'mleczny', 'samica', '2026-04-07'),
    (1, 'PL142001037', 'bydlo', 'Simmental', 'miesny', 'samica', '2026-04-29'),
    (1, 'PL142001038', 'bydlo', 'Simmental', 'miesny', 'samiec', '2026-05-16'),
    (1, 'PL142001039', 'bydlo', 'Limousin', 'miesny', 'samica', '2026-06-02'),
    (1, 'PL142001040', 'bydlo', 'HF', 'ogolnouzytkowy', 'samica', '2026-07-14');


INSERT INTO machines (farm_id, type, name, model, manufacture) VALUES
(1, 'ciągnik', 'Ciągnik główny', 'John Deere 6155M', 2019),
(1, 'ciągnik', 'Ciągnik pomocniczy', 'New Holland T6.180', 2017),
(1, 'kombajn', 'Kombajn zbożowy', 'Claas Tucano 430', 2016),
(1, 'pług', 'Pług obracalny', 'Kverneland 150 B', 2018),
(1, 'siewnik', 'Siewnik zbożowy', 'Amazone D9 4000', 2020),
(1, 'agregat', 'Agregat uprawowy', 'Unia Atlas 4.0', 2019),
(1, 'opryskiwacz', 'Opryskiwacz polowy', 'Krukowiak Herkules 2500', 2021),
(1, 'kosiarka', 'Kosiarka dyskowa', 'Kuhn GMD 3511', 2018),
(1, 'prasa', 'Prasa zwijająca', 'Claas Rollant 455', 2017),
(1, 'przyczepa', 'Przyczepa rolnicza', 'Pronar T672', 2020);


INSERT INTO fieldwork (field_id, type_of_work, method, date, cost) VALUES
(1, 'orka', 'wlasna', '2025-09-18', 420.00),
(1, 'talerzowanie', 'wlasna', '2025-09-20', 260.00),
(1, 'siew', 'wlasna', '2025-09-25', 180.00),
(1, 'nawozenie', 'wlasna', '2026-03-18', 150.00),
(1, 'oprysk', 'usluga_zewnetrzna', '2026-04-22', 480.00),
(2, 'orka', 'usluga_zewnetrzna', '2025-09-14', 720.00),
(2, 'siew', 'wlasna', '2025-09-22', 300.00),
(2, 'nawozenie', 'wlasna', '2026-03-25', 240.00),
(2, 'oprysk', 'wlasna', '2026-05-10', 190.00),
(2, 'zbior', 'usluga_zewnetrzna', '2026-08-29', 950.00),
(3, 'koszenie', 'wlasna', '2026-06-15', 160.00),
(3, 'zgrabianie', 'wlasna', '2026-06-16', 90.00),
(3, 'prasowanie', 'usluga_zewnetrzna', '2026-06-18', 320.00);

INSERT INTO financial_records (farm_id, type, category, amount, performer, date, info) VALUES
(1, 'przychod', 'sprzedaz', 18500.00, 'Młyn Rolny Północ', '2025-08-30', 'Sprzedaż pszenicy'),
(1, 'przychod', 'sprzedaz', 9200.00, 'Paszarnia Zielona', '2025-10-12', 'Sprzedaż kukurydzy'),
(1, 'przychod', 'sprzedaz', 6400.00, 'Skup Rolny Piła', '2026-08-31', 'Sprzedaż zboża'),
(1, 'przychod', 'sprzedaz', 7800.00, 'Mleczarnia Nadnotecka', '2026-08-31', 'Sprzedaż mleka'),
(1, 'przychod', 'inne', 2100.00, 'ARiMR', '2026-05-20', 'Płatność związana z gospodarstwem'),
(1, 'koszt', 'paliwo', 3200.00, 'Stacja AgroFuel', '2025-04-10', 'Paliwo do maszyn'),
(1, 'koszt', 'nawozy', 5100.00, 'Agro-Centrum', '2025-03-22', 'Nawozy mineralne'),
(1, 'koszt', 'sor', 2700.00, 'Agro-Centrum', '2025-05-03', 'Środki ochrony roślin'),
(1, 'koszt', 'zakup', 4300.00, 'Skład Rolny', '2025-08-12', 'Zakup materiału siewnego'),
(1, 'koszt', 'uslugi', 1850.00, 'Usługi Rolnicze Kowalski', '2025-09-14', 'Usługa orki'),
(1, 'koszt', 'paliwo', 2900.00, 'Stacja AgroFuel', '2026-04-05', 'Paliwo do maszyn'),
(1, 'koszt', 'nawozy', 4800.00, 'Agro-Centrum', '2026-03-15', 'Nawozy pod uprawy'),
(1, 'koszt', 'sor', 2200.00, 'Agro-Centrum', '2026-04-20', 'Środki ochrony roślin'),
(1, 'koszt', 'uslugi', 2600.00, 'Usługi Rolnicze Kowalski', '2026-08-29', 'Usługa zbioru'),
(1, 'koszt', 'inne', 750.00, 'Sklep Rolniczy', '2026-02-11', 'Części i drobne wyposażenie');

-- ==========
-- END
-- ==========
